import type { RowData } from "~components/FilePanel";
import cover from "../../src/renderer/resources/cover.jpg";

export const rows: RowData[] = [
    {
        filename: "01 - Happens To The Heart.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "Happens To The Heart",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 1,
        year: 2019,
        length: 273,
        size: 22749256,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "02 - Moving On.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "Moving On",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 2,
        year: 2019,
        length: 192,
        size: 14556156,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "03 - The Night of Santiago.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "The Night of Santiago",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 3,
        year: 2019,
        length: 255,
        size: 20998200,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "04 - Thanks For The Dance.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "Thanks For The Dance",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 4,
        year: 2019,
        length: 253,
        size: 18920215,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "05 - It's Torn.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "It's Torn",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 5,
        year: 2019,
        length: 178,
        size: 13998876,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "06 - The Goal.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "The Goal",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 6,
        year: 2019,
        length: 72,
        size: 5576134,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "07 - Puppets.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "Puppets",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 7,
        year: 2019,
        length: 160,
        size: 12369996,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "08 - The Hills.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "The Hills",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 8,
        year: 2019,
        length: 258,
        size: 25574353,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    },
    {
        filename: "09 - Listen To The Hummingbird.flac",
        path: "D:\\Music\\Leonard Cohen\\2019 - Thanks For The Dance\\",
        tag: "FLAC",
        title: "Listen To The Hummingbird",
        artist: "Leonard Cohen",
        album: "Thanks For The Dance",
        track: 9,
        year: 2019,
        length: 121,
        size: 7459732,
        lastModified: 1574467200000,
        lyrics: undefined,
        thumbnail: cover
    }
];
