name: New dependencies advisor

on:
  pull_request:
    branches:
      - main

jobs:
  new-dependencies-advisor:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: New dependencies advisor
        uses: lirantal/github-action-new-dependencies-advisor@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
