name: Node CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup NodeJS
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Dependencies Install
      run: npm ci
      env:
        CI: true

    - name: Build and Test
      run: npm run build
      env:
        CI: true
        APISEEDS_KEY: ${{ secrets.APISEEDS_KEY }}
        HAPPI_DEV_KEY: ${{ secrets.HAPPI_DEV_KEY }}

    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: installer/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
