name: Node CI

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Setup NodeJS
      uses: actions/setup-node@v2.1.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependencies Install
      run: npm ci
      env:
        CI: true

    - name: Build and Test
      run: npm run build
      env:
        CI: true

    - name: Codecov
      uses: codecov/codecov-action@v1.0.10
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: installer/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
