name: Node CI

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependencies Install
      run: npm ci
      env:
        CI: true

    - name: Build and Test
      run: npm run build
      env:
        CI: true

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: installer/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
